LCFIPlus: lcfiplus::Jet Class Reference
lcfiplus::Jet Class Reference
#include <lcfiplus.h>
Public Member Functions
Jet ()
Jet (const Track *trk)
Jet (const Neutral *neutral)
Jet (const Vertex *vtx)
Jet (const Jet &from, bool extractVertex=false)
~Jet ()
void setId (int id) const
int getId () const
const vector< const Track * > & getTracks () const
const vector< const Neutral * > & getNeutrals () const
const vector< const Vertex * > & getVertices () const
vector< const Vertex * > getVerticesForFT () const
returns list of vertices which are useful for flavor tagging.
vector< const Track * > getAllTracks (bool withoutV0=false) const
returns list of all tracks including those used to form vertices.
void add (const Jet &jet)
void add (const Track *trk)
void add (const Neutral *neut)
void add (const Vertex *vtx, bool removeTracks=true)
double sphericity () const
void addParam (const char *paramname, Parameters &param) const
const Parameters * getParam (const char *paramname) const
const map< string, Parameters > & params () const
void recalcFourMomentum ()
Static Public Member Functions
static int sort_by_energy (const Jet *a, const Jet *b)
Constructor & Destructor Documentation
lcfiplus::Jet::Jet () inline
lcfiplus::Jet::Jet (const Track * trk)
lcfiplus::Jet::Jet (const Neutral * neutral)
lcfiplus::Jet::Jet (const Vertex * vtx) inline
lcfiplus::Jet::Jet (const Jet & from, bool extractVertex = false)
References getNeutrals(), getTracks(), getVertices(), and params().
lcfiplus::Jet::~Jet () inline
Member Function Documentation
void lcfiplus::Jet::add (const Jet & jet)
References getNeutrals(), getTracks(), and getVertices().
Referenced by lcfiplus::convertJetVertex(), findAdditionalVertices(), matchMcVertex(), lcfiplus::JetFinder::prerun(), lcfiplus::VertexMassRecovery::process(), and lcfiplus::LCIOStorer::ReadJets().
void lcfiplus::Jet::add (const Track * trk) inline
void lcfiplus::Jet::add (const Neutral * neut) inline
void lcfiplus::Jet::add (const Vertex * vtx, bool removeTracks = true) inline
References lcfiplus::Vertex::getTracks().
void lcfiplus::Jet::addParam (const char * paramname, Parameters & param) const inline
Referenced by lcfiplus::JetClustering::process(), lcfiplus::FTManager::process(), and lcfiplus::LCIOStorer::ReadJets().
vector< const Track * > lcfiplus::Jet::getAllTracks (bool withoutV0 = false) const
returns list of all tracks including those used to form vertices.
if withoutV0 is true, skip tracks which are identified as v0 (default: false)
References lcfiplus::Event::getPrimaryVertex(), lcfiplus::Vertex::getTracks(), getTracks(), getVertices(), lcfiplus::Event::Instance(), and lcfiplus::Vertex::passesV0selection().
Referenced by lcfiplus::algoSigProb::findMostSignificantTrack(), lcfiplus::algoSigProb::jointProb2D0(), lcfiplus::algoSigProb::jointProb2Z0(), lcfiplus::algoSigProb::jointProbD0(), lcfiplus::algoSigProb::jointProbZ0(), lcfiplus::TrackNtuple::process(), lcfiplus::ZHHAlgo::process(), lcfiplus::TestAlgo::process(), and sphericity().
int lcfiplus::Jet::getId () const inline
const vector<const Neutral*>& lcfiplus::Jet::getNeutrals () const inline
Referenced by add(), lcfiplus::convertJetVertex(), Jet(), and lcfiplus::LCIOStorer::WriteJets().
const Parameters* lcfiplus::Jet::getParam (const char * paramname) const inline
Referenced by lcfiplus::ZHHAlgo::process(), lcfiplus::FlavtagReader::process(), lcfiplus::ZHHAlgo::sortBtag(), and lcfiplus::LCIOStorer::WritePID().
const vector<const Track*>& lcfiplus::Jet::getTracks () const inline
Referenced by add(), lcfiplus::convertJetVertex(), findAdditionalVertices(), lcfiplus::LcfiInterface::findSecondaryVertices(), findSingleTracks(), lcfiplus::findTearDownVertices(), lcfiplus::LcfiInterface::forceZvtop(), getAllTracks(), Jet(), lcfiplus::algoSigProb::jointProb2D0(), lcfiplus::algoSigProb::jointProb2Z0(), lcfiplus::algoSigProb::jointProbD0(), lcfiplus::algoSigProb::jointProbZ0(), matchMcVertexJet(), testSuehara(), and lcfiplus::LCIOStorer::WriteJets().
const vector<const Vertex*>& lcfiplus::Jet::getVertices () const inline
Referenced by add(), lcfiplus::convertJetVertex(), lcfiplus::JetFinder::funcVertex(), getAllTracks(), getVerticesForFT(), Jet(), lcfiplus::JetFinder::prerun(), lcfiplus::VertexNtuple::process(), lcfiplus::ZHHAlgo::process(), lcfiplus::TestAlgo::process(), and lcfiplus::LCIOStorer::WriteJets().
vector< const Vertex * > lcfiplus::Jet::getVerticesForFT () const
returns list of vertices which are useful for flavor tagging.
References lcfiplus::Vertex::dist_sort(), lcfiplus::Vertex::getTracks(), and getVertices().
const map<string, Parameters>& lcfiplus::Jet::params () const inline
Referenced by Jet(), and lcfiplus::LCIOStorer::WriteAllPIDs().
void lcfiplus::Jet::recalcFourMomentum () inline
Referenced by lcfiplus::ZHHAlgo::process().
void lcfiplus::Jet::setId (int id) const inline
Referenced by lcfiplus::LCIOStorer::ReadJets(), and lcfiplus::LCIOStorer::WriteJets().
static int lcfiplus::Jet::sort_by_energy (const Jet * a, const Jet * b) inline static
Referenced by lcfiplus::JetFinder::run().
double lcfiplus::Jet::sphericity () const
References getAllTracks().
The documentation for this class was generated from the following files:
lcfiplus.h
lcfiplus.cc