LCFIPlus: lcfiplus::VertexFinderTearDown< Container, VertexFitter > Class Template Reference
lcfiplus::VertexFinderTearDown< Container, VertexFitter > Class Template Reference
#include <VertexFinderTearDown.h>
Public Member Functions
Vertex * operator() (const Container< const Track * > &tracks, const Container< const Track * > *fixedTracks=0, double chiSquareThreshold=9.0, Container< const Track * > *residual=0, Vertex *pointConstraint=0)
Member Function Documentation
template<template< class T, class Allocator=allocator< T > > class Container = std::vector, template< class Iterator > class VertexFitter = VertexFitterLCFI> Vertex* lcfiplus::VertexFinderTearDown< Container, VertexFitter >::operator() (const Container< const Track * > & tracks, const Container< const Track * > * fixedTracks = 0, double chiSquareThreshold = 9.0, Container< const Track * > * residual = 0, Vertex * pointConstraint = 0) inline
References lcfiplus::Vertex::getChi2Track(), lcfiplus::Vertex::getTracksChi2Map(), and lcfiplus::Vertex::getWorstTrack().
The documentation for this class was generated from the following file:
VertexFinderTearDown.h