LCFIPlus: lcfiplus::Neutral Class Reference
lcfiplus::Neutral Class Reference
#include <lcfiplus.h>
Public Member Functions
Neutral ()
~Neutral ()
int getId () const
void setId (int id)
const lcfiplus::MCParticle * getMcp () const
void setMcp (const lcfiplus::MCParticle *mcp)
int getPDG () const
void setPDG (int pdg)
const double * getCaloEdep () const
void setCaloEdep (double *calo)
bool isV0 () const
void setV0 (bool v0=true)
void setClusters (EVENT::ClusterVec clu)
EVENT::ClusterVec getClusters () const
Constructor & Destructor Documentation
lcfiplus::Neutral::Neutral () inline
lcfiplus::Neutral::~Neutral () inline
Member Function Documentation
const double* lcfiplus::Neutral::getCaloEdep () const inline
EVENT::ClusterVec lcfiplus::Neutral::getClusters () const inline
Referenced by lcfiplus::Pi0VertexFinder::Make_GammaVector().
int lcfiplus::Neutral::getId () const inline
const lcfiplus::MCParticle* lcfiplus::Neutral::getMcp () const inline
int lcfiplus::Neutral::getPDG () const inline
Referenced by matchMcVertexRecoV0().
bool lcfiplus::Neutral::isV0 () const inline
Referenced by matchMcVertexRecoV0().
void lcfiplus::Neutral::setCaloEdep (double * calo) inline
Referenced by lcfiplus::LCIOStorer::SetEvent().
void lcfiplus::Neutral::setClusters (EVENT::ClusterVec clu) inline
Referenced by lcfiplus::LCIOStorer::SetEvent().
void lcfiplus::Neutral::setId (int id) inline
Referenced by lcfiplus::LCIOStorer::SetEvent().
void lcfiplus::Neutral::setMcp (const lcfiplus::MCParticle * mcp) inline
Referenced by lcfiplus::LCIOStorer::SetEvent().
void lcfiplus::Neutral::setPDG (int pdg) inline
Referenced by lcfiplus::LCIOStorer::SetEvent().
void lcfiplus::Neutral::setV0 (bool v0 = true) inline
Referenced by lcfiplus::LCIOStorer::SetEvent().
The documentation for this class was generated from the following file:
lcfiplus.h