LCFIPlus: lcfiplus::JetFinder Class Reference
lcfiplus::JetFinder Class Reference
Finds jets using various jet clustering algorithms.
#include <JetFinder.h>
Public Member Functions
JetFinder (const JetConfig &cfg, const Vertex *ip=0)
Constructor.
~JetFinder ()
Destructor.
void Configure (const JetConfig &cfg)
Replace JetConfig.
vector< Jet * > run (TrackVec &tracks)
Perform jet clustering with charged tracks only.
vector< Jet * > run (TrackVec &tracks, NeutralVec &neutrals, double *pymin=0, int ynjetmax=10)
Perform jet clustering using both charged tracks and neutral particles.
vector< Jet * > run (TrackVec &tracks, NeutralVec &neutrals, VertexVec &vertices, double *pymin=0, int ynjetmax=10)
Perform jet clustering using charged tracks and neutral particles with the contraint that the given vertices are not merged.
vector< Jet * > prerun (TrackVec &tracks, NeutralVec &neutrals, VertexVec &vertices, int *pnVertexJets=0)
Lepton finder and vertex isolator/combiner, called from run() with vertices.
vector< Jet * > run (vector< Jet * > input, double *pymin=0, int ynjetmax=10)
Main function of jet clustering, called from other run() functions.
Static Public Member Functions
static double funcDurham (Jet &jet1, Jet &jet2, double Evis2, JetConfig &cfg)
static double funcJade (Jet &jet1, Jet &jet2, double Evis2, JetConfig &cfg)
static double funcJadeE (Jet &jet1, Jet &jet2, double Evis2, JetConfig &cfg)
static double funcDurhamCheat (Jet &jet1, Jet &jet2, double Evis2, JetConfig &cfg)
static double funcKt (Jet &jet1, Jet &jet2, double Evis2, JetConfig &cfg)
static double funcValencia (Jet &jet1, Jet &jet2, double Evis2, JetConfig &cfg)
static double funcVertex (Jet &jet1, Jet &jet2, double Evis2, JetConfig &cfg, double(*func)(Jet &, Jet &, double, JetConfig &))
static double funcDurhamVertex (Jet &jet1, Jet &jet2, double Evis2, JetConfig &cfg)
static double funcKtVertex (Jet &jet1, Jet &jet2, double Evis2, JetConfig &cfg)
static double funcValenciaVertex (Jet &jet1, Jet &jet2, double Evis2, JetConfig &cfg)
static double funcDurhamBeamDistance (Jet &jet, double Evis2, JetConfig &cfg)
static double funcKtBeamDistance (Jet &jet, double Evis2, JetConfig &cfg)
static double funcValenciaBeamDistance (Jet &jet, double Evis2, JetConfig &cfg)
Detailed Description
Finds jets using various jet clustering algorithms.
Author
T. Tanabe, ICEPP, The University of Tokyo
T. Suehara, ICEPP, The University of Tokyo
Version
$Id$
Constructor & Destructor Documentation
lcfiplus::JetFinder::JetFinder (const JetConfig & cfg, const Vertex * ip = 0)
Constructor.
Parameters
[in] cfg specify the algorithm and the parameters
lcfiplus::JetFinder::~JetFinder () inline
Destructor.
Member Function Documentation
void lcfiplus::JetFinder::Configure (const JetConfig & cfg)
Replace JetConfig.
Parameters
[in] cfg specify the algorithm and the parameters
double lcfiplus::JetFinder::funcDurham (Jet & jet1, Jet & jet2, double Evis2, JetConfig & cfg) static
References lcfiplus::algoEtc::min().
Referenced by prerun().
double lcfiplus::JetFinder::funcDurhamBeamDistance (Jet & jet, double Evis2, JetConfig & cfg) static
References lcfiplus::JetConfig::alphaParameter.
Referenced by prerun().
double lcfiplus::JetFinder::funcDurhamCheat (Jet & jet1, Jet & jet2, double Evis2, JetConfig & cfg) static
References lcfiplus::algoEtc::min().
double lcfiplus::JetFinder::funcDurhamVertex (Jet & jet1, Jet & jet2, double Evis2, JetConfig & cfg) static
Referenced by prerun().
double lcfiplus::JetFinder::funcJade (Jet & jet1, Jet & jet2, double Evis2, JetConfig & cfg) static
double lcfiplus::JetFinder::funcJadeE (Jet & jet1, Jet & jet2, double Evis2, JetConfig & cfg) static
double lcfiplus::JetFinder::funcKt (Jet & jet1, Jet & jet2, double Evis2, JetConfig & cfg) static
References lcfiplus::algoEtc::min(), and lcfiplus::JetConfig::rParameter.
Referenced by prerun().
double lcfiplus::JetFinder::funcKtBeamDistance (Jet & jet, double Evis2, JetConfig & cfg) static
Referenced by prerun().
double lcfiplus::JetFinder::funcKtVertex (Jet & jet1, Jet & jet2, double Evis2, JetConfig & cfg) static
Referenced by prerun().
double lcfiplus::JetFinder::funcValencia (Jet & jet1, Jet & jet2, double Evis2, JetConfig & cfg) static
References lcfiplus::JetConfig::betaParameter, lcfiplus::algoEtc::min(), and lcfiplus::JetConfig::rParameter.
Referenced by prerun().
double lcfiplus::JetFinder::funcValenciaBeamDistance (Jet & jet, double Evis2, JetConfig & cfg) static
References lcfiplus::JetConfig::betaParameter, and lcfiplus::JetConfig::gammaParameter.
Referenced by prerun().
double lcfiplus::JetFinder::funcValenciaVertex (Jet & jet1, Jet & jet2, double Evis2, JetConfig & cfg) static
Referenced by prerun().
double lcfiplus::JetFinder::funcVertex (Jet & jet1, Jet & jet2, double Evis2, JetConfig & cfg, double(*)(Jet &, Jet &, double, JetConfig &) func) static
References lcfiplus::Jet::getVertices(), lcfiplus::JetConfig::YaddLL, lcfiplus::JetConfig::YaddVL, and lcfiplus::JetConfig::YaddVV.
vector< Jet * > lcfiplus::JetFinder::prerun (TrackVec & tracks, NeutralVec & neutrals, VertexVec & vertices, int * pnVertexJets = 0)
Lepton finder and vertex isolator/combiner, called from run() with vertices.
References lcfiplus::Vertex::add(), lcfiplus::Jet::add(), lcfiplus::JetConfig::algo, funcDurham(), funcDurhamBeamDistance(), funcDurhamVertex(), funcKt(), funcKtBeamDistance(), funcKtVertex(), funcValencia(), funcValenciaBeamDistance(), funcValenciaVertex(), lcfiplus::Vertex::getMcp(), lcfiplus::Track::getParticleIDProbability(), lcfiplus::MCParticle::getPDG(), lcfiplus::Vertex::getPos(), lcfiplus::Jet::getVertices(), lcfiplus::Vertex::getX(), lcfiplus::Vertex::getY(), lcfiplus::Vertex::getZ(), lcfiplus::MCParticle::isParent(), lcfiplus::JetConfig::muonIDExternal, lcfiplus::JetConfig::muonIDMaxDist, lcfiplus::JetConfig::muonIDMinD0Sig, lcfiplus::JetConfig::muonIDMinEnergy, lcfiplus::JetConfig::muonIDMinProb, lcfiplus::JetConfig::muonIDMinZ0Sig, lcfiplus::JetConfig::nJet, lcfiplus::algoEtc::SimpleSecMuonFinder(), and lcfiplus::JetConfig::useMuonID.
Referenced by run().
vector< Jet * > lcfiplus::JetFinder::run (TrackVec & tracks)
Perform jet clustering with charged tracks only.
Referenced by run().
vector< Jet * > lcfiplus::JetFinder::run (TrackVec & tracks, NeutralVec & neutrals, double * pymin = 0, int ynjetmax = 10)
Perform jet clustering using both charged tracks and neutral particles.
References run().
vector< Jet * > lcfiplus::JetFinder::run (TrackVec & tracks, NeutralVec & neutrals, VertexVec & vertices, double * pymin = 0, int ynjetmax = 10)
Perform jet clustering using charged tracks and neutral particles with the contraint that the given vertices are not merged.
References prerun(), and run().
vector< Jet * > lcfiplus::JetFinder::run (vector< Jet * > input, double * pymin = 0, int ynjetmax = 10)
Main function of jet clustering, called from other run() functions.
References lcfiplus::algoEtc::min(), lcfiplus::JetConfig::nJet, lcfiplus::Jet::sort_by_energy(), lcfiplus::JetConfig::useBeamJets, and lcfiplus::JetConfig::Ycut.
The documentation for this class was generated from the following files:
JetFinder.h
JetFinder.cc