LCFIPlus: lcfiplus::Helix Class Reference
lcfiplus::Helix Class Reference
#include <geometry.h>
Classes
class HelixLineDistance2DerivFunctor
class HelixLineDistance2Functor
class VarianceDerivFunctor
class VarianceFunctor
Public Types
enum par {
id0 =0, iz0, iph, iom,
itd, parN
}
typedef ROOT::Math::SVector
< double, 5 > SVector5
typedef ROOT::Math::SVector
< double, 3 > SVector3
typedef ROOT::Math::SMatrix
< double,
5, 5, ROOT::Math::MatRepSym
< double, 5 > > SMatrixSym5
typedef ROOT::Math::SMatrix
< double, 5, 3 > SMatrix53
typedef ROOT::Math::SMatrix
< double, 3, 5 > SMatrix35
typedef ROOT::Math::SMatrix
< double,
3, 3, ROOT::Math::MatRepSym
< double, 3 > > SMatrixSym3
typedef ROOT::Math::SMatrix
< double, 3, 3 > SMatrix3
Public Types inherited from lcfiplus::PointBase
enum FITFLAG { NOTUSED, PRIVTX, SECVTX }
Public Member Functions
virtual double LogLikelihood (const TVector3 &p) const
double LogLikelihood (const TVector3 &p, double &tmin) const
void LogLikelihoodDeriv (const TVector3 &p, double *output) const
double Variance (const TVector3 &p, double t) const
double VarianceDeriv (const TVector3 &p, double t) const
double VarianceDeriv2 (const TVector3 &p, double t) const
TVector3 GetPos (double t) const
TVector3 GetPosDerivT (double t) const
void GetPosErr (double t, SVector3 &pos, SMatrixSym3 &err) const
void GetPosErr (double t, SVector3 &pos, SMatrixSym3 &err, SMatrix53 &trackToXyz) const
void GetPosErrDeriv (double t, SVector3 &pos, SMatrixSym3 &err) const
void GetPosErrDeriv2 (double t, SVector3 &pos, SMatrixSym3 &err) const
double LongitudinalDeviation (const Vertex *ip, const Vertex *sec)
Helix (FITFLAG flag)
Helix (const SVector5 &hel, const SMatrixSym5 &err, int charge, FITFLAG flag)
Helix (const Track *trk, FITFLAG flag)
Helix (const Helix &ref, FITFLAG flag)
~Helix ()
void GetCenter (double &x, double &y) const
void FindZCross (double x, double y, double &zi, double &zp) const
TVector3 ClosePoint (const Helix &hel) const
TVector3 ClosePoint (const VertexLine &line, double *distance=0) const
Public Member Functions inherited from lcfiplus::PointBase
virtual ~PointBase ()
Additional Inherited Members
Protected Member Functions inherited from lcfiplus::PointBase
PointBase (FITFLAG flag)
FITFLAG GetFlag () const
Protected Attributes inherited from lcfiplus::PointBase
FITFLAG _fitflag
Member Typedef Documentation
typedef ROOT::Math::SMatrix<double, 3,3> lcfiplus::Helix::SMatrix3
typedef ROOT::Math::SMatrix<double, 3,5> lcfiplus::Helix::SMatrix35
typedef ROOT::Math::SMatrix<double, 5,3> lcfiplus::Helix::SMatrix53
typedef ROOT::Math::SMatrix<double, 3,3,ROOT::Math::MatRepSym<double,3> > lcfiplus::Helix::SMatrixSym3
typedef ROOT::Math::SMatrix<double, 5,5,ROOT::Math::MatRepSym<double,5> > lcfiplus::Helix::SMatrixSym5
typedef ROOT::Math::SVector<double, 3> lcfiplus::Helix::SVector3
typedef ROOT::Math::SVector<double, 5> lcfiplus::Helix::SVector5
Member Enumeration Documentation
enum lcfiplus::Helix::par
Enumerator
id0
iz0
iph
iom
itd
parN
Constructor & Destructor Documentation
lcfiplus::Helix::Helix (FITFLAG flag) inline
lcfiplus::Helix::Helix (const SVector5 & hel, const SMatrixSym5 & err, int charge, FITFLAG flag) inline
lcfiplus::Helix::Helix (const Track * trk, FITFLAG flag)
References lcfiplus::tpar::d0d0, lcfiplus::tpar::d0om, lcfiplus::tpar::d0ph, lcfiplus::tpar::d0td, lcfiplus::tpar::d0z0, lcfiplus::Track::getCharge(), lcfiplus::Track::getCovMatrix(), lcfiplus::Track::getD0(), lcfiplus::Track::getOmega(), lcfiplus::Track::getPhi(), lcfiplus::Track::getTanLambda(), lcfiplus::Track::getZ0(), id0, iom, iph, itd, iz0, lcfiplus::tpar::omom, lcfiplus::tpar::omtd, lcfiplus::tpar::phom, lcfiplus::tpar::phph, lcfiplus::tpar::phtd, lcfiplus::tpar::tdtd, lcfiplus::tpar::z0om, lcfiplus::tpar::z0ph, lcfiplus::tpar::z0td, and lcfiplus::tpar::z0z0.
lcfiplus::Helix::Helix (const Helix & ref, FITFLAG flag) inline
lcfiplus::Helix::~Helix () inline
Member Function Documentation
TVector3 lcfiplus::Helix::ClosePoint (const Helix & hel) const
References ClosePoint(), FindZCross(), GetCenter(), iom, LogLikelihood(), and lcfiplus::verbose.
Referenced by lcfiplus::VertexFinderSuehara::associateIPTracksAVF(), ClosePoint(), and LongitudinalDeviation().
TVector3 lcfiplus::Helix::ClosePoint (const VertexLine & line, double * distance = 0) const
References FindZCross(), GetCenter(), GetPos(), iom, itd, iz0, lcfiplus::algoEtc::min(), and lcfiplus::verbose.
void lcfiplus::Helix::FindZCross (double x, double y, double & zi, double & zp) const
References lcfiplus::tpar::d0, id0, iom, iph, itd, iz0, and lcfiplus::tpar::z0.
Referenced by ClosePoint(), and LogLikelihood().
void lcfiplus::Helix::GetCenter (double & x, double & y) const
References lcfiplus::tpar::d0, id0, iom, and iph.
Referenced by ClosePoint().
TVector3 lcfiplus::Helix::GetPos (double t) const
References lcfiplus::tpar::d0, id0, iom, iph, itd, iz0, and lcfiplus::tpar::z0.
Referenced by ClosePoint(), and lcfiplus::Helix::HelixLineDistance2Functor::operator()().
TVector3 lcfiplus::Helix::GetPosDerivT (double t) const
References iom, iph, and itd.
Referenced by lcfiplus::Track::momentumAtVertex().
void lcfiplus::Helix::GetPosErr (double t, SVector3 & pos, SMatrixSym3 & err) const
Referenced by Variance(), VarianceDeriv(), and VarianceDeriv2().
void lcfiplus::Helix::GetPosErr (double t, SVector3 & pos, SMatrixSym3 & err, SMatrix53 & trackToXyz) const
References lcfiplus::tpar::d0, id0, iom, iph, itd, iz0, and lcfiplus::tpar::z0.
void lcfiplus::Helix::GetPosErrDeriv (double t, SVector3 & pos, SMatrixSym3 & err) const
References lcfiplus::tpar::d0, id0, iom, iph, itd, iz0, and lcfiplus::tpar::z0.
Referenced by VarianceDeriv(), and VarianceDeriv2().
void lcfiplus::Helix::GetPosErrDeriv2 (double t, SVector3 & pos, SMatrixSym3 & err) const
References lcfiplus::tpar::d0, id0, iom, iph, and itd.
Referenced by VarianceDeriv2().
virtual double lcfiplus::Helix::LogLikelihood (const TVector3 & p) const inline virtual
Implements lcfiplus::PointBase.
Referenced by ClosePoint(), lcfiplus::VertexFitterSimple< Iterator >::getChi2(), lcfiplus::Track::momentumAtVertex(), and lcfiplus::VertexFitterSimple< Iterator >::operator()().
double lcfiplus::Helix::LogLikelihood (const TVector3 & p, double & tmin) const
References lcfiplus::brent(), lcfiplus::dbrent(), FindZCross(), lcfiplus::PointBase::GetFlag(), lcfiplus::golden(), iom, itd, iz0, lcfiplus::algoEtc::min(), lcfiplus::PointBase::PRIVTX, lcfiplus::PointBase::SECVTX, Variance(), VarianceDeriv(), VarianceDeriv2(), lcfiplus::verbose, and lcfiplus::tpar::z0.
void lcfiplus::Helix::LogLikelihoodDeriv (const TVector3 & p, double * output) const virtual
Implements lcfiplus::PointBase.
double lcfiplus::Helix::LongitudinalDeviation (const Vertex * ip, const Vertex * sec)
References ClosePoint(), lcfiplus::Point::GetPos(), lcfiplus::Vertex::getPos(), lcfiplus::GeometryHandler::Instance(), lcfiplus::PointBase::NOTUSED, lcfiplus::GeometryHandler::PointFit(), lcfiplus::PointBase::SECVTX, and lcfiplus::verbose.
Referenced by lcfiplus::FtVtxLongitudinalDeviation::process().
double lcfiplus::Helix::Variance (const TVector3 & p, double t) const
References GetPosErr().
Referenced by LogLikelihood(), and lcfiplus::Helix::VarianceFunctor::operator()().
double lcfiplus::Helix::VarianceDeriv (const TVector3 & p, double t) const
References GetPosErr(), and GetPosErrDeriv().
Referenced by LogLikelihood(), and lcfiplus::Helix::VarianceDerivFunctor::operator()().
double lcfiplus::Helix::VarianceDeriv2 (const TVector3 & p, double t) const
References GetPosErr(), GetPosErrDeriv(), and GetPosErrDeriv2().
Referenced by LogLikelihood().
The documentation for this class was generated from the following files:
geometry.h
geometry.cc